language: php
php:
  - '7.4'
  - '8.0'

sudo:     true

addons:
  mariadb: '10.2'

before_install:
  - pecl install inotify
  - mysql --version
  - mysql -u root -e "set global binlog_format = 'row';"
  - mysql -u root -e "set global log_bin_trust_function_creators = 1;"
  - sudo locale-gen en_US
  - sudo locale-gen en_US.utf8
  - sudo locale-gen nl_NL
  - sudo locale-gen nl_NL.utf8
  - sudo locale-gen nl_BE
  - sudo locale-gen nl_BE.utf8

install:
  - composer self-update
  - composer update

script:
  - ./bin/phing unit
