/**
 * Selects the value of a text in a language.
 *
 * @param p_txt_id The ID of the text.
 * @param p_lan_id The ID of the language.
 *
 * @type singleton1 varchar
 */
create procedure abc_babel_core_text_get_text
(
  in p_txt_id smallint(5) unsigned, -- type: ABC_BABEL_TEXT_TEXT.txt_id
  in p_lan_id tinyint(3) unsigned --   type: ABC_BABEL_TEXT_TEXT.lan_id
)
  reads sql data
begin
  select ttt_text
  from ABC_BABEL_TEXT_TEXT
  where txt_id = p_txt_id
    and lan_id = p_lan_id;
end
