/**
 * Selects the value of a word in a language.
 *
 * @param p_wrd_id The ID of the word.
 * @param p_lan_id The ID of the language.
 *
 * @type singleton1 varchar
 */
create procedure abc_babel_core_word_get_word
(
  in p_wrd_id smallint(5) unsigned, -- type: ABC_BABEL_WORD_TEXT.wrd_id
  in p_lan_id tinyint(3) unsigned --   type: ABC_BABEL_WORD_TEXT.lan_id
)
  reads sql data
begin
  select wdt_text
  from ABC_BABEL_WORD_TEXT
  where wrd_id = p_wrd_id
    and lan_id = p_lan_id;
end
