/**
 * Selects the value of a word in a language.
 *
 * @param p_wrd_id The ID of the word.
 * @param p_lan_id The ID of the language.
 */
create procedure abc_babel_word_get_word(in p_wrd_id @bbl_word.wrd_id%type@
,                                        in p_lan_id @bbl_language.lan_id%type@)
reads sql data
-- type: singleton1
begin
  select wdt_text
  from   BBL_WORD_TEXT
  where  wrd_id = p_wrd_id
  and    lan_id = p_lan_id
  ;
end
